# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b928921abcb9cfba9a711082c7b16aae46ce8cee494805dc27ec324651b2192aa9a3f14b7b46b58cb5101908f49e7efbafdcca88429c746c402f14d27301c0

test:
  secret_key_base: 2aa5ecd31c561760591443d3d291e9b97bd149b64e76be07e3d05e4fd1f5c9b486855f515c80a8af03a07d9f285dc21a937a6e4a6a062107994b70c15d833d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
